/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LangIndexRouteImport } from './app/$lang/index'
import { Route as LangTodosRouteImport } from './app/$lang/todos'
import { Route as LangAboutRouteImport } from './app/$lang/about'

const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTodosRoute = LangTodosRouteImport.update({
  id: '/$lang/todos',
  path: '/$lang/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$lang/about': typeof LangAboutRoute
  '/$lang/todos': typeof LangTodosRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/$lang/about': typeof LangAboutRoute
  '/$lang/todos': typeof LangTodosRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang/about': typeof LangAboutRoute
  '/$lang/todos': typeof LangTodosRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$lang/about' | '/$lang/todos' | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$lang/about' | '/$lang/todos' | '/$lang'
  id: '__root__' | '/$lang/about' | '/$lang/todos' | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangTodosRoute: typeof LangTodosRoute
  LangIndexRoute: typeof LangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/todos': {
      id: '/$lang/todos'
      path: '/$lang/todos'
      fullPath: '/$lang/todos'
      preLoaderRoute: typeof LangTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangTodosRoute: LangTodosRoute,
  LangIndexRoute: LangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
